---
- name: "Creating Ec2 instance and Updating Route53 records"
  hosts: local
  connection: local
  vars:
    ami_id: "ami-09c813fb71547fc4f"
    instance_type: "t3.micro"
    sg_group_id: "sg-0242bb58b998464f3"
    hosted_zone_id: "Z0242709XHWMRVUKV1M5"
    domain_name: "devops-phani.fun"
    # While creating instances we need to change the below list as for our requirement , so this approach is static
    # Dynamically we can pass through command line like below , we can give multiple server in the below array
    # ansible-playbook -i inventory.ini <file-name> -e "instances=['<servername>','<servername>']"
    instances:
    - frontend
    - backend 
    - database
  tasks:
  - name: "Create Ec2 instances"
    amazon.aws.ec2_instance:
      name: "{{ item }}"
      image_id: "{{ ami_id }}"
      # security_group: "{{ sg_group_id }}"
      security_group_ids:
        - "{{ sg_group_id }}"
      instance_type: "{{ instance_type }}"
      tags:
        name: "{{ item }}"
    loop: "{{ instances }}"
    register: ec2_output

  - name: "Creating Route53 if frontend"
    amazon.aws.route53:
      state: present
      zone_id: "{{ hosted_zone_id }}"
      record: "{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].public_ip_address }}"
      overwrite: true
    when: item.item == "frontend"
    loop: "{{ ec2_output.results }}"

  - name: "Creating Route53 if not frontend"
    amazon.aws.route53:
      state: present
      zone_id: "{{ hosted_zone_id }}"
      record: "{{ item.item }}.{{ domain_name }}"
      type: A
      ttl: 1
      value: "{{ item.instances[0].private_ip_address }}"
      overwrite: true
    loop: "{{ ec2_output.results }}"
    when: item.item != "frontend"

