- name: "Frontend setup"
  hosts: frontend 
  connection: frontend 
  become: yes
  tasks:
  - name: "Install nginx"
    ansible.builtin.package: 
      name: nginx 
      state: present 
  - name: "Remove the default content"
    ansible.builtin.file:
      state: absent
      path: /usr/share/nginx/html/
  - name: "Creating html folder"
    ansible.builtin.file:
      path: /usr/share/nginx/html/
      state: directory
  - name: "Download frontend code"
    ansible.builtin.get_url:
      url: https://expense-joindevops.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip
  - name: "Unzip code or Extracting"
    ansible.builtin.unarchive:
      src: /tmp/frontend.zip
      dest: /usr/share/nginx/html/
      remote_src: yes
  - name: "Remove or delete default expense.conf"
    ansible.builtin.file:
      path: /etc/nginx/expense.conf
      state: absent
  - name: copy expense conf
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/expense.conf 
  - name: restart nginx
    ansible.builtin.service:
      name: nginx
      state: restarted # restarted if you have already started earlier
      enabled: yes